 services:
  crud:
    image: crud-service
    build:
      context: .
      dockerfile: CRUD/Dockerfile
    ports:
      - "14440:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12761276k
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Logging__Loglevel__Default=Debug
      - ASPNETCORE_Logging__Loglevel__Microsoft.AspNetCore=Debug
    volumes:
      - ~/.aspnet/https:/https:ro  
    