 
 services:
  crud:
    image: crud-service
    build:
      context: .
      dockerfile: CRUD/Dockerfile
    ports:
      - "14446:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12761276k
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Logging__Loglevel__Default=Debug
      - Logging__Loglevel__Microsoft=Warning
      - Logging__Loglevel__Microsoft.AspNetCore=Debug
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - backend
  
 networks:
   backend:
     driver: bridge

    